### ISSUE TITLE
코드 수정 요청 사항 

### ISSUE THREAD

**Issue by snoopspy** [song21677/pcap_test#1]
https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302812

https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302816

https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302818

https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302840

https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302860

https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302873

https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302879

https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302894

https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302789

**Comment by song21677** [comment]
> [b68deb3#r38302812](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302812)
> 
> [b68deb3#r38302816](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302816)
> 
> [b68deb3#r38302818](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302818)
> 
> [b68deb3#r38302840](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302840)
> 
> [b68deb3#r38302860](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302860)
> 
> [b68deb3#r38302873](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302873)
> 
> [b68deb3#r38302879](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302879)
> 
> [b68deb3#r38302894](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302894)
> 
> [b68deb3#r38302789](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302789)

전부 수정하였습니다!
https://github.com/song21677/pcap_test/commit/9f142476552b2bf576d2e0ba23afffb10968ea2e

**Comment by song21677** [comment]
> [b68deb3#r38302812](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302812)
> 
> [b68deb3#r38302816](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302816)
> 
> [b68deb3#r38302818](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302818)
> 
> [b68deb3#r38302840](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302840)
> 
> [b68deb3#r38302860](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302860)
> 
> [b68deb3#r38302873](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302873)
> 
> [b68deb3#r38302879](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302879)
> 
> [b68deb3#r38302894](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302894)
> 
> [b68deb3#r38302789](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38302789)

전부 수정하였습니다!
https://github.com/song21677/pcap_test/commit/9f142476552b2bf576d2e0ba23afffb10968ea2e

**Comment by snoopspy** [comment]
각각의 comment에 "Done in ..." 달아 주세요.

**Comment by song21677** [comment]
> 각각의 comment에 "Done in ..." 달아 주세요.

각각의 comment에 "Done in ..." 달아 주었습니다!

**Comment by snoopspy** [comment]
수고하셨습니다.
