### ISSUE TITLE
코드 수정 요청 사항(2)

### ISSUE THREAD

**Issue by snoopspy** [song21677/pcap_test#2]
https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38313990

https://github.com/song21677/pcap_test/commit/9f142476552b2bf576d2e0ba23afffb10968ea2e#r38314047

https://github.com/song21677/pcap_test/commit/9f142476552b2bf576d2e0ba23afffb10968ea2e#r38314098

**Comment by song21677** [comment]
> [b68deb3#r38313990](https://github.com/song21677/pcap_test/commit/b68deb332eda10ac079ae6cba510678ceaf638ee#r38313990)
> 
> [9f14247#r38314047](https://github.com/song21677/pcap_test/commit/9f142476552b2bf576d2e0ba23afffb10968ea2e#r38314047)
> 
> [9f14247#r38314098](https://github.com/song21677/pcap_test/commit/9f142476552b2bf576d2e0ba23afffb10968ea2e#r38314098)

전부 수정하였습니다!
https://github.com/song21677/pcap-test/commit/ee813a2d560a7b3468363da41ddc26951617d1a1

**Comment by snoopspy** [comment]
수고하셨습니다.
